#!/bin/bash

echo "[mysql-init] Criando usuários e permissões..."

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF

-- Usuário GLPI
CREATE USER IF NOT EXISTS '${MYSQL_GLPI_USE}'@'%' IDENTIFIED BY '${MYSQL_GLPI_PASSWORD}';
GRANT ALL PRIVILEGES ON glpi.* TO '${MYSQL_GLPI_USE}'@'%';

-- Usuário Zabbix
CREATE USER IF NOT EXISTS '${MYSQL_ZBX_USE}'@'%' IDENTIFIED BY '${MYSQL_ZBX_PASSWORD}';
GRANT ALL PRIVILEGES ON zabbix.* TO '${MYSQL_ZBX_USE}'@'%';

-- Usuário Grafana
CREATE USER IF NOT EXISTS '${MYSQL_GRAFANA_USE}'@'%' IDENTIFIED BY '${MYSQL_GRAFANA_PASSWORD}';
GRANT ALL PRIVILEGES ON grafana.* TO '${MYSQL_GRAFANA_USE}'@'%';

FLUSH PRIVILEGES;
EOF

echo "[mysql-init] Finalizado!"
