#!/bin/bash

echo "[mysql-init] Criando usuários e permissões..."

mysql -u root -p"${MYSQL_ROOT_PASSWORD}" <<EOF

-- Usuário GLPI
CREATE USER IF NOT EXISTS '${MYSQL_GLPI_USER}'@'%' IDENTIFIED BY '${MYSQL_GLPI_PASSWORD}';
GRANT ALL PRIVILEGES ON glpi.* TO '${MYSQL_GLPI_USER}'@'%';

-- Usuário Zabbix
CREATE USER IF NOT EXISTS '${MYSQL_ZBX_USER}'@'%' IDENTIFIED BY '${MYSQL_ZBX_PASSWORD}';
GRANT ALL PRIVILEGES ON zabbix.* TO '${MYSQL_ZBX_USER}'@'%';

-- Usuário Grafana
CREATE USER IF NOT EXISTS '${MYSQL_GRAFANA_USER}'@'%' IDENTIFIED BY '${MYSQL_GRAFANA_PASSWORD}';
GRANT ALL PRIVILEGES ON grafana.* TO '${MYSQL_GRAFANA_USER}'@'%';

-- Usuário NGiNX
CREATE USER IF NOT EXISTS '${MYSQL_NGINX_USER}'@'%' IDENTIFIED BY '${MYSQL_NGINX_PASSWORD}';
GRANT ALL PRIVILEGES ON grafana.* TO '${MYSQL_NGINX_USER}'@'%';

-- Usuário BSKP
CREATE USER IF NOT EXISTS '${MYSQL_BSKP_USER}'@'%' IDENTIFIED BY '${MYSQL_BSKP_PASSWORD}';
GRANT ALL PRIVILEGES ON grafana.* TO '${MYSQL_BSKP_USER}'@'%';

FLUSH PRIVILEGES;
EOF

echo "[mysql-init] Finalizado!"
